# Generated by Django 3.2.9 on 2021-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_owner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethistory',
            name='admit_date',
            field=models.DateField(auto_now_add=True, verbose_name='Admit date'),
        ),
        migrations.AlterField(
            model_name='pethistory',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release date'),
        ),
    ]
