# Generated by Django 3.2.9 on 2021-12-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20211210_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
