# Generated by Django 3.2.9 on 2021-12-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pethistory',
            name='admit_date',
        ),
        migrations.RemoveField(
            model_name='pethistory',
            name='release_date',
        ),
    ]
