# Generated by Django 3.2.9 on 2021-12-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20211211_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcost',
            name='room_charge',
        ),
    ]
